#import "lib.typ": *

#heading(level: 1, numbering: none, outlined: true)[فهرست اختصارات]

#acronyms-list((
  ("ACK", "Acknowledge"),
  ("ADR", "Adaptive Data Rate"),
  ("bps", "bits per second"),
  ("BW", "Bandwidth"),
  ("CF", "Carrier Frequency"),
  ("CR", "Code Rate"),
  ("CSS", "Chirp Spread Spectrum"),
  ("DER", "Data Extraction Rate"),
  ("FEC", "Forward Error Correction"),
  ("IoT", "Internet of Things"),
  ("JS", "Join Server"),
  ("LoRa", "Long Range"),
  ("LoRaWAN", "Long Range Wide Area Network"),
  ("MAC", "Medium Access Control"),
  ("LPWAN", "Low Power Wide Area Network"),
  ("NB-IoT", "Narrow band Internet of Things"),
  ("NS", "Network Server"),
  ("PDR", "Packet Delivery Ratio"),
  ("PER", "Packet Error Ratio"),
  ("PLR", "Packet Loss Ratio"),
  ("RF", "Radio Frequency"),
  ("RW", "Receive Window"),
  ("SF", "Spreading Factor"),
  ("SNR", "Signal to Noise Ratio"),
  ("ToA", "Time on Air"),
  ("TDC", "Transmission Duty Cycle"),
  ("ABP", "Activation by Personalization"),
  ("TP", "Transmission Power"),
  ("UL", "Uplink"),
  ("DL", "Downlink"),
  ("OTAA", "Over-the-Air Activation"),
  ("LR-FHSS", "Long Range — Frequency Hopping Spread Spectrum"),
  ("SCHC", "Static Context Header Compression"),
  ("AQD", "Air Quality Detector"),
  ("CRC", "Cyclic Redundancy Check"),
  ("ISM", "Industrial Scientific Medical"),
  ("RSSI", "Received Signal Strength Indication"),
  ("RTT", "Round Trip Time"),
  ("NTP", "Network Time Protocol"),
  ("PTP", "Precision Time Protocol"),
  ("M2M", "Machine-to-Machine"),
  ("WSN", "Wireless Sensor Networks"),
  ("3GPP", "3rd Generation Partnership Project"),
  ("IIoT", "Industrial Internet of Things"),
  ("REST", "Representational State Transfer"),
  ("CRUD", "Create, Retrieve, Update and Delete"),
  ("CoAP", "Constrained Application Protocol"),
  ("MQTT", "Message Queue Telemetry Transport"),
  ("AMQP", "Advanced Messaging Queue Protocol"),
  ("CBOR", "Concise Binary Object Representation"),
  ("JSON", "Javascript Object Notation"),
  ("RPC", "Remote Procedure Call"),
  ("UTC", "Coordinated Universal Time"),
  ("API", "Application Programming Interface"),
  ("ROA", "Resource Oriented Architecture"),
  ("URI", "Uniform Resource Identifier"),
  ("TAS", "Thing Adaption Software"),
  ("OID", "Object Identifier"),
  ("SBEMS", "Smart Building Energy Management System"),
  ("MSS", "Maximum Segment Size"),
  ("IGP", "Internet Gateway Placement"),
  ("AoI", "Age of Information"),
))
