#import "lib.typ": *

#heading(level: 1, numbering: none, outlined: true)[واژه‌نامه]

#glossary-list((
  ("Coverage", "پوشش‌دهی"),
  ("KPI", "شاخص کلیدی عملکرد"),
  ("Network", "شبکه"),
  ("Node", "گره"),
  ("Handshake", "دست‌داد"),
  ("Performance", "کارآیی"),
  ("Precision Agriculture", "کشاورزی دقیق"),
  ("Telemetry", "دورسنجی"),
  ("Trade-off", "مصالحه"),
  ("Encoding", "کدگذاری"),
  ("Publisher", "منتشرکننده"),
  ("Publish", "انتشار"),
  ("Subscribe", "اشتراک"),
  ("Adaptive", "تطبیقی/تطبق‌پذیر"),
  ("Date Rate", "نرخ داده"),
  ("Multi-Hop", "چندگامه"),
  ("End Device", "دستگاه انتهایی"),
  ("Use Case", "کاربرد"),
  ("Sensor", "حسگر"),
  ("sub-GHz", "زیر گیگاهرتز"),
  ("Integration", "ادغام"),
  ("Message Broker", "کارگزار پیام"),
  ("Thread", "نخ"),
  ("Roaming", "فراگرد"),
  ("Stream", "جریان"),
  ("Fragmentation", "قطعه‌بندی"),
  ("Spatial Pooling", "ادغام مکانی"),
  ("Carrier Sense", "حس حامل"),
  ("Exponential Back- off", "عقب‌نشینی نمایی"),
  ("Recurrent", "بازرخداد"),
  ("Preamble", "پیشایند"),
  ("Forward Error Control", "کنترل خطا جلورونده"),
  ("Spreading Factor", "فاکور گسترش"),
  ("Auto Encoder", "خودکدگذار"),
  ("Topology", "همبندی‌"),
  ("Cloud Native", "ابرزی"),
  ("Real-time", "همزمان"),
  ("Variational", "تغییراتی"),
  ("Self-Configuring", "خودپیکربندی"),
  ("Interoperable", "هم‌کنشپذیر"),
  ("Tail Latency", "دم تاخیر"),
  ("Fog Computing", "پردازش مِه"),
  ("Mist Computing", "پردازش غبار"),
  ("Data Trimming", "پاک کردن داده‌ها"),
  ("User Equipment", "دستگاه کاربر"),
  ("Ad-Hoc", "تک‌کاره"),
  ("Beacon", "علامت راهنمایی"),
  ("Emulation", "تقلید"),
  ("Constrained Networks", "شبکه‌های محدود"),
  ("Adaption Layer", "لایه سازگاری"),
  ("Self-Sustaining", "خود نگهدارنده"),
  ("Data Model", "ساختار داده‌ای، ساختار اطلاعاتی"),
  ("Data Encoding", "کدگذاری داده"),
  ("Heuristic", "ابتکاری"),
  ("Meta-Heuristic", "فرا ابتکاری"),
  ("Age of Information", "عمر اطلاعات"),
))
